import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { managedDatabasePluginPresets, databasePluginModelRevision, resolveDatabasePluginConnection, isPrivateDatabasePluginAddress, assertDatabasePluginPublicUrl, probeDatabasePluginModels, requestDatabasePluginCompletion, databasePluginChatSse, validateDatabasePluginChatPayload } from "../server/database-plugin-models.ts";
const fixture=()=>{const cwd=mkdtempSync(join(tmpdir(),"liyuan-model-bridge-"));writeFileSync(join(cwd,"liyuan.agent.json"),JSON.stringify({version:1,defaultProvider:"enabled",defaultModel:"gemini-3.7-flash",providers:{enabled:{api:"openai-completions",baseUrl:"http://127.0.0.1:12345/v1",apiKey:"SYNTHETIC_SERVER_KEY",models:[{id:"gemini-3.7-flash"},{id:"gemini-3.8-flash",maxTokens:32768}]}}}));return {cwd,cleanup:()=>rmSync(cwd,{recursive:true,force:true})};};
test("database managed presets reference active connections without exporting secrets or changing the main model",()=>{const f=fixture();try{const ref={provider:"enabled",id:"gemini-3.8-flash"};const list=managedDatabasePluginPresets(f.cwd,{fillModel:ref,recallModel:ref});assert.equal(list.length,2);assert.equal(list[0].maxTokens,16384);assert.equal(list[1].maxTokens,8192);assert.ok(!JSON.stringify(list).includes("SYNTHETIC_SERVER_KEY"));assert.ok(!JSON.stringify(list).includes("12345"));assert.notEqual(databasePluginModelRevision(list),databasePluginModelRevision([]));assert.equal(managedDatabasePluginPresets(f.cwd,{fillModel:{provider:"warehouse-only",id:ref.id}}).length,0);}finally{f.cleanup()}});
test("database connections allow explicit active private gateways, but reject unknown aliases",()=>{const f=fixture();try{assert.equal(resolveDatabasePluginConnection(f.cwd,"/api/database-plugin/connections/recall/enabled/v1").purpose,"recall");assert.equal(resolveDatabasePluginConnection(f.cwd,"http://127.0.0.1:12345/v1").managed,true);assert.equal(resolveDatabasePluginConnection(f.cwd,"https://example.test/v1").managed,false);assert.throws(()=>resolveDatabasePluginConnection(f.cwd,"/api/database-plugin/connections/fill/warehouse/v1"),/未启用/);}finally{f.cleanup()}});
test("database unknown endpoints reject SSRF ranges, URL credentials, redirects and masked keys",async()=>{for(const address of ["127.0.0.1","10.0.0.1","192.168.1.1","172.17.0.2","169.254.169.254","100.64.0.1","::1","fc00::1","fe80::2","::ffff:127.0.0.1"])assert.equal(isPrivateDatabasePluginAddress(address),true,address);assert.equal(isPrivateDatabasePluginAddress("8.8.8.8"),false);await assert.rejects(assertDatabasePluginPublicUrl("https://127.0.0.1/v1"),/私有/);await assert.rejects(assertDatabasePluginPublicUrl("http://example.test/v1"),/HTTPS/);const f=fixture();try{await assert.rejects(probeDatabasePluginModels(f.cwd,{custom_url:"https://example.test/v1",custom_include_headers:"Authorization: Bearer host-managed"},{publicUrl:async()=>{},fetch:async()=>{throw new Error("must not send host key")}}),/没有绑定/);}finally{f.cleanup()}});
test("original model-status payload produces an actual OpenAI model list with server-side credentials",async()=>{const f=fixture();try{let calls=0;const result=await probeDatabasePluginModels(f.cwd,{chat_completion_source:"custom",custom_url:"/api/database-plugin/connections/fill/enabled/v1",custom_include_headers:"Authorization: Bearer host-managed"},{fetch:async(url,options)=>{calls++;assert.equal(url,"http://127.0.0.1:12345/v1/models");assert.equal((options?.headers as any).authorization,"Bearer SYNTHETIC_SERVER_KEY");assert.equal(options?.redirect,"error");return new Response(JSON.stringify({data:[{id:"gemini-3.8-flash"},{id:"gemini-3.8-flash"}]}));}});assert.equal(calls,1);assert.deepEqual(result.data,[{id:"gemini-3.8-flash",object:"model"}]);assert.equal(result.source,"upstream");assert.ok(!JSON.stringify(result).includes("KEY"));}finally{f.cleanup()}});
test("custom draft model-status keeps explicit user authentication and preserves failure statuses",async()=>{const f=fixture();try{await probeDatabasePluginModels(f.cwd,{custom_url:"https://example.test/v1",custom_include_headers:"Authorization: Bearer OWN_DRAFT_KEY"},{publicUrl:async()=>{},fetch:async(_,options)=>{assert.equal((options?.headers as any).authorization,"Bearer OWN_DRAFT_KEY");return new Response(JSON.stringify({models:["model-one"]}));}});await assert.rejects(probeDatabasePluginModels(f.cwd,{custom_url:"/api/database-plugin/connections/fill/enabled/v1"},{fetch:async()=>new Response('upstream must not leak credential text',{status:401})}),/HTTP 401/);await assert.rejects(probeDatabasePluginModels(f.cwd,{custom_url:"/api/database-plugin/connections/fill/enabled/v1"},{fetch:async()=>new Response('{"data":[]}')}),/为空/);}finally{f.cleanup()}});
test("managed completion uses the exact enabled model and returns original text/tool schema",async()=>{const f=fixture();try{let invoked=0;const payload={custom_url:"/api/database-plugin/connections/recall/enabled/v1",model:"gemini-3.8-flash",messages:[{role:"user",content:"synthetic recall"}]};const reply=await requestDatabasePluginCompletion(f.cwd,payload,{}, {complete:async(body,options)=>{invoked++;assert.equal(body,payload);assert.deepEqual(options.modelRef,{provider:"enabled",id:"gemini-3.8-flash"});assert.equal(options.purpose,"recall");return {model:"gemini-3.8-flash",choices:[{index:0,message:{role:"assistant",content:"<keywords>synthetic</keywords>",tool_calls:[{id:"call",type:"function",function:{name:"table_edit",arguments:'{"commands":""}'}}]},finish_reason:"tool_calls"}]};}});assert.equal(invoked,1);assert.equal(reply.choices[0].finish_reason,"tool_calls");assert.match(databasePluginChatSse(reply),/data: \[DONE\]/);assert.match(databasePluginChatSse(reply),/table_edit/);await assert.rejects(requestDatabasePluginCompletion(f.cwd,{...payload,model:"not-enabled"},{},{complete:async()=>{throw new Error("must not call")}}),/模型清单/);}finally{f.cleanup()}});
test("masked stored custom preset keys are restored only for the same endpoint and model",async()=>{const f=fixture();try{const payload={custom_url:"https://example.test/v1",model:"custom",messages:[{role:"user",content:"synthetic"}],custom_include_headers:"Authorization: Bearer host-managed"};const settings={profile:JSON.stringify({apiPresets:[{apiConfig:{url:payload.custom_url,model:"custom",apiKey:"STORED_SYNTHETIC_KEY"}}]})};const result=await requestDatabasePluginCompletion(f.cwd,payload,settings,{publicUrl:async()=>{},fetch:async(_,options)=>{assert.equal((options?.headers as any).authorization,"Bearer STORED_SYNTHETIC_KEY");const body=JSON.parse(options?.body as string);assert.equal(body.stream,false);return new Response(JSON.stringify({choices:[{message:{content:"synthetic result"},finish_reason:"stop"}]}));}});assert.equal(result.choices[0].message.content,"synthetic result");await assert.rejects(requestDatabasePluginCompletion(f.cwd,{...payload,model:"different"},settings,{publicUrl:async()=>{}}),/鉴权未保存/);}finally{f.cleanup()}});
test("database request validation refuses invalid messages and malformed tools",()=>{assert.throws(()=>validateDatabasePluginChatPayload({messages:[{role:"developer",content:"not supported"}]}),/消息/);assert.throws(()=>validateDatabasePluginChatPayload({messages:[{role:"user",content:"ok"}],tools:[{type:"function",function:{name:"bad"}}]}),/工具/);});

test("a registered private gateway honors explicit user auth during model-status without applying public-only rules",async()=>{const f=fixture();try{const result=await probeDatabasePluginModels(f.cwd,{custom_url:"http://127.0.0.1:12345/v1",custom_include_headers:"Authorization: Bearer EXPLICIT_ACCOUNT_KEY"},{fetch:async(_,options)=>{assert.equal((options?.headers as any).authorization,"Bearer EXPLICIT_ACCOUNT_KEY");return new Response('{"data":[{"id":"gemini-3.8-flash"}]}');},publicUrl:async()=>{throw new Error("registered connection must not be rejected")}});assert.equal(result.data[0].id,"gemini-3.8-flash");}finally{f.cleanup()}});

test("a source change during auth/DNS validation prevents later network/model invocation",async()=>{const f=fixture();try{let valid=true,calls=0;await assert.rejects(probeDatabasePluginModels(f.cwd,{custom_url:"/api/database-plugin/connections/fill/enabled/v1"},{auth:async()=>{valid=false;return{apiKey:"NO_SEND"}},guard:()=>{if(!valid)throw new Error("source changed")},fetch:async()=>{calls++;return new Response('{}')}}),/source changed/);assert.equal(calls,0);valid=true;await assert.rejects(requestDatabasePluginCompletion(f.cwd,{custom_url:"https://example.test/v1",model:"fixture",messages:[{role:"user",content:"synthetic"}]},{},{publicUrl:async()=>{valid=false},fetch:async()=>{calls++;return new Response('{}')}},undefined,()=>{if(!valid)throw new Error("source changed")}),/source changed/);assert.equal(calls,0);}finally{f.cleanup()}});

test("custom body YAML is bounded, honors extra/excluded fields, and cannot change model or transcript",async()=>{const f=fixture();try{const payload={custom_url:"https://example.test/v1",model:"fixture",messages:[{role:"user",content:"synthetic transcript"}],custom_include_body:'temperature: 0.4\nseed: 7\nmodel: attacker-model\nmessages: []',custom_exclude_body:'seed'};await requestDatabasePluginCompletion(f.cwd,payload,{}, {publicUrl:async()=>{},fetch:async(_,options)=>{const body=JSON.parse(options?.body as string);assert.equal(body.temperature,0.4);assert.equal(body.seed,undefined);assert.equal(body.model,"fixture");assert.equal(body.messages[0].content,"synthetic transcript");return new Response('{"choices":[{"message":{"content":"ok"}}]}');}});}finally{f.cleanup()}});
