import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { DatabasePluginHttp } from '../server/database-plugin-http.ts';
function fixture(){const cwd=mkdtempSync(join(tmpdir(),'liyuan-plugin-http-'));let ctx={scope:{sessionId:'synthetic',card:'card-a.json'},sourceEntryId:'a-1',visibleEntryIds:['a-1'],chat:[{__liyuanEntryId:'a-1',message_id:'a-1',mes:'Synthetic committed story',is_user:false}],character:{name:'Synthetic'},userName:'User'};let streaming=false,calls=0;const api=new DatabasePluginHttp(cwd,{context:()=>ctx,isStreaming:()=>streaming,generate:async()=>{calls++;return 'SYNTHETIC_RESPONSE'}});return {cwd,api,context:()=>ctx,switch:(next:any)=>{ctx=next},stream:(v:boolean)=>{streaming=v},calls:()=>calls,cleanup:()=>rmSync(cwd,{recursive:true,force:true})};}
const emptyState={messages:{},chatMetadata:{},extensionSettings:{},worldbooks:{}};
test('database plugin HTTP: scoped CAS state, branch filtering, canonical transcript is never writable',async()=>{const f=fixture();try{const c=await f.api.context();await f.api.save({...c,state:{...emptyState,messages:{'a-1':{TavernDB_ACU_Data:{synthetic:true}}},worldbooks:{[c.primaryBook]:{entries:[{uid:1,comment:'synthetic',content:'Synthetic anchor',enabled:true,type:'constant'}]}}}});assert.ok((await f.api.context()).chat[0].TavernDB_ACU_Data);await assert.rejects(f.api.save({...c,state:emptyState}),/revision/i);await assert.rejects(f.api.save({...await f.api.context(),state:{...emptyState,messages:{'a-1':{mes:'rewritten'}}}}),/message|extension|forbidden/i);const sibling={...f.context(),sourceEntryId:'sibling',visibleEntryIds:['sibling'],chat:[{mes:'Synthetic sibling',__liyuanEntryId:'sibling',message_id:'sibling',is_user:false}]};f.switch(sibling);const read=await f.api.context();assert.ok(!read.chat[0].TavernDB_ACU_Data);assert.equal((await f.api.injection('Synthetic')).length,0);}finally{f.cleanup()}});
test('database plugin HTTP: delayed binding cannot write to a different session/card/source',async()=>{const f=fixture();try{const c=await f.api.context();f.switch({...f.context(),scope:{sessionId:'other',card:'card-b.json'}});await assert.rejects(f.api.save({...c,state:emptyState}),/会话|分支/);assert.equal((await f.api.context()).revision,0);}finally{f.cleanup()}});
test('database plugin HTTP: original transcript GET and model routing do not expose credentials',async()=>{const f=fixture();const server=createServer((req,res)=>{void f.api.handle(req,res).then(handled=>{if(!handled){res.writeHead(404);res.end()}})});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));try{const base='http://127.0.0.1:'+(server.address() as any).port;const c=await f.api.context();const response=await fetch(base+'/api/database-plugin/generate',{method:'POST',body:JSON.stringify({...c,prompts:[{role:'user',content:'Synthetic test'}]})});assert.equal(response.status,200);assert.deepEqual(await response.json(),{text:'SYNTHETIC_RESPONSE'});assert.equal(f.calls(),1);const raw=await(await fetch(base+'/api/database-plugin/native-chat')).json();assert.equal(raw[1].mes,'Synthetic committed story');f.stream(true);const denied=await fetch(base+'/api/database-plugin/state',{method:'POST',body:JSON.stringify({...c,state:emptyState})});assert.equal(denied.status,400);assert.equal((await f.api.context()).revision,0);const unknown=await fetch(base+'/api/database-plugin/external',{method:'POST',body:JSON.stringify({...c,url:'https://unregistered.invalid/',payload:{}})});assert.equal(unknown.status,400);}finally{await new Promise<void>(r=>server.close(()=>r()));f.cleanup()}});
test('database plugin HTTP: manual extra knowledge uses plugin artifacts, keeps generated table rows protected',async()=>{const f=fixture();try{await f.api.addMemory('Synthetic manual background that is not a story event','Synthetic');const catalogue=await f.api.listMemory();assert.equal(catalogue.length,1);assert.equal(catalogue[0].meta.source,'database-plugin');assert.equal(await f.api.deleteMemory(catalogue[0].id),true);assert.equal((await f.api.listMemory()).length,0);}finally{f.cleanup()}});
test('database plugin HTTP: nested/serialized upstream keys stay server-side and masked save preserves them',async()=>{const f=fixture();try{const c=await f.api.context();const secret='SYNTHETIC_SERVER_ONLY_CREDENTIAL';await f.api.save({...c,state:{...emptyState,extensionSettings:{__userscripts:{fixture:{global:JSON.stringify({vectorMemoryConfigGlobal:{embeddingApiKey:secret,rerankApiKey:secret}})}}}}});const view=await f.api.context();assert.ok(!JSON.stringify(view).includes(secret));const current=await f.api.store.readState(f.context().scope,f.context().visibleEntryIds);assert.ok(JSON.stringify(current.snapshot?.state).includes(secret));await f.api.save({...view,state:{...emptyState,extensionSettings:view.extensionSettings}});const after=await f.api.store.readState(f.context().scope,f.context().visibleEntryIds);assert.ok(JSON.stringify(after.snapshot?.state).includes(secret));}finally{f.cleanup()}});
test('database plugin HTTP: same object name in siblings is immutable-pointer isolated; delete only hides current branch',async()=>{const f=fixture();try{const a=await f.api.context();await f.api.putObject({...a,name:'same.json',data:Buffer.from('{"branch":"A"}').toString('base64')});const origin=f.context();f.switch({...origin,sourceEntryId:'b-1',visibleEntryIds:['b-1'],chat:[{mes:'Synthetic branch B',__liyuanEntryId:'b-1',message_id:'b-1',is_user:false}]});assert.equal(await f.api.readObject('same.json'),null);const b=await f.api.context();await f.api.putObject({...b,name:'same.json',data:Buffer.from('{"branch":"B"}').toString('base64')});assert.equal((await f.api.readObject('same.json'))?.data.toString(),'{"branch":"B"}');assert.equal(await f.api.deleteObject({...b,name:'same.json'}),true);assert.equal(await f.api.readObject('same.json'),null);f.switch(origin);assert.equal((await f.api.readObject('same.json'))?.data.toString(),'{"branch":"A"}');}finally{f.cleanup()}});
test('provider switch stops old SDK narrative auto-writes without altering old memory config',async()=>{const {mkdirSync,writeFileSync}=await import('node:fs');const {onNarrativeTurnEnd,updateMemoryConfig,memoryUpsertEventDigest,memoryArchiveCompacted}=await import('../src/memory/service.ts');const f=fixture();try{updateMemoryConfig(f.cwd,{enabled:true,embedMode:'local'});mkdirSync(join(f.cwd,'.liyuan-database-plugin'),{recursive:true});writeFileSync(join(f.cwd,'.liyuan-database-plugin','config.json'),'{"enabled":true}');const scope={sessionId:'synthetic'};assert.equal((await onNarrativeTurnEnd(f.cwd,scope,'Synthetic old SDK narration that must not enter the old library')).stored,false);assert.equal((await memoryArchiveCompacted(f.cwd,scope,'Synthetic archive that must not enter the old library')).archived,false);assert.equal((await memoryUpsertEventDigest(f.cwd,scope,{kind:'rp-event-digest',id:'synthetic',title:'Synthetic',status:'active',importance:'major',tags:[],recallAnchors:[],summary:'Synthetic event',sourceRefs:[{entryId:'a-1'}],evidenceLevel:'source-backed'})).stored,false);}finally{f.cleanup()}});
