import assert from 'node:assert/strict';import test from 'node:test';
import {createDatabasePluginGenerator} from '../server/database-plugin-generation.ts';
const baseModel={id:'gemini-3.8-flash',provider:'enabled',api:'openai-completions',maxTokens:16384,compat:{supportsTools:true}};
function fakeDependencies(result:any={role:'assistant',content:[{type:'text',text:'synthetic response'}],usage:{input:3,output:4,totalTokens:7},stopReason:'stop'}){
 const calls:any[]=[];const deps={findModel:(ref:any)=>ref.provider==='enabled'&&ref.id===baseModel.id?baseModel:undefined,defaultModel:()=>baseModel,auth:async()=>({ok:true,apiKey:'SERVER_ONLY_KEY',headers:{}}),stream:((model:any,context:any,options:any)=>{calls.push({model,context,options});return {async *[Symbol.asyncIterator](){yield{type:'done',message:result}},async result(){return result}}}) as any};return{calls,deps};
}
test('database generator resolves exact Flash 3.8 and keeps authentication out of reply',async()=>{const f=fakeDependencies();const generate=createDatabasePluginGenerator(f.deps);const reply=await generate([{role:'system',content:'synthetic instructions'},{role:'user',content:'synthetic context'}],undefined,{modelRef:{provider:'enabled',id:baseModel.id},payload:{max_tokens:8192,temperature:.5}});assert.equal(reply.model,baseModel.id);assert.equal(reply.choices[0].message.content,'synthetic response');assert.equal(f.calls[0].options.apiKey,'SERVER_ONLY_KEY');assert.equal(f.calls[0].options.maxTokens,8192);assert.equal(f.calls[0].options.reasoning,'off');assert.ok(!JSON.stringify(reply).includes('SERVER_ONLY_KEY'));});
test('database generator native tool calls round-trip into original OpenAI response schema',async()=>{const f=fakeDependencies({content:[{type:'toolCall',id:'tool-1',name:'table_edit',arguments:{commands:'insertRow(0,{"0":"synthetic"})'}}],usage:{input:1,output:2,totalTokens:3},stopReason:'toolUse'});const reply=await createDatabasePluginGenerator(f.deps)([{role:'user',content:'synthetic'}],undefined,{payload:{tools:[{type:'function',function:{name:'table_edit',parameters:{type:'object',properties:{commands:{type:'string'}}}}}]}});assert.equal(f.calls[0].context.tools[0].name,'table_edit');assert.equal(reply.choices[0].finish_reason,'tool_calls');assert.equal(JSON.parse(reply.choices[0].message.tool_calls![0].function.arguments).commands,'insertRow(0,{"0":"synthetic"})');});
test('database generator honors declared tools support, authentication, errors, and late binding before dispatch',async()=>{const f=fakeDependencies();const options={payload:{tools:[{type:'function',function:{name:'table_edit',parameters:{type:'object'}}}]}};const off={...f.deps,defaultModel:()=>({...baseModel,compat:{supportsTools:false}})};await assert.rejects(createDatabasePluginGenerator(off)([{role:'user',content:'synthetic'}],undefined,options),/不支持工具/);await assert.rejects(createDatabasePluginGenerator({...f.deps,auth:async()=>({ok:false})})([{role:'user',content:'synthetic'}]),/鉴权不可用/);await assert.rejects(createDatabasePluginGenerator(f.deps)([{role:'user',content:'synthetic'}],undefined,{validateBinding:()=>{throw new Error('stale source')}}),/stale source/);assert.equal(f.calls.length,0);const failed=fakeDependencies({stopReason:'error',content:[],usage:{}});await assert.rejects(createDatabasePluginGenerator(failed.deps)([{role:'user',content:'synthetic'}]),/没有完成/);});
