import type { Browser, Page } from "playwright";
import { chromium } from "playwright";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { DatabasePluginHttp } from "./database-plugin-http.ts";
export class DatabasePluginRuntime {
 private browser:Browser|null=null;private page:Page|null=null;private scope='';private source='';private busy:Promise<unknown>=Promise.resolve();private binding:{scopeKey:string;sourceEntryId:string}|null=null;
 readonly http:DatabasePluginHttp; readonly origin:()=>string;
 constructor(http:DatabasePluginHttp,origin:()=>string){this.http=http;this.origin=origin;}
 async close(){await this.browser?.close();this.browser=null;this.page=null;this.scope='';this.source='';}
 private async ensure(){const context=this.http.currentContext(),scope=this.http.scopeKey(context);this.binding={scopeKey:scope,sourceEntryId:context.sourceEntryId};if(this.page&&scope===this.scope&&context.sourceEntryId===this.source)return this.page;await this.close();this.http.sources.readCurrentPinnedJS();this.browser=await chromium.launch({headless:true,...((process.env.LIYUAN_DATABASE_BROWSER_EXECUTABLE||existsSync(join(this.http.root,'browser','headless_shell')))?{executablePath:process.env.LIYUAN_DATABASE_BROWSER_EXECUTABLE||join(this.http.root,'browser','headless_shell')}:{}),env:{...process.env,LD_LIBRARY_PATH:process.env.LIYUAN_DATABASE_BROWSER_LIBS??process.env.LD_LIBRARY_PATH??(existsSync(join(this.http.root,'browser-libs','lib64'))?join(this.http.root,'browser-libs','lib64'):'')},args:process.getuid?.()===0?['--no-sandbox']:[]});const bc=await this.browser.newContext();await bc.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.origin!==this.origin())return route.abort('blockedbyclient');return route.continue({headers:{...req.headers(),'x-liyuan-database-host':this.http.internalToken,'x-liyuan-database-scope':this.binding?.scopeKey??'','x-liyuan-database-source':this.binding?.sourceEntryId??''}})});this.page=await bc.newPage();this.page.on('dialog',dialog=>{if(dialog.type()==='confirm'&&/向量方案已优化，需要重建/.test(dialog.message()))void dialog.accept();else void dialog.dismiss();});this.scope=scope;this.source=context.sourceEntryId;await this.page.goto(this.origin()+'/database-plugin-host.html');try{await this.page.waitForFunction(()=>!!(window as any).LiyuanDatabasePluginHost?.ready(),{},{timeout:60000});}catch{const message=await this.page.evaluate(()=>document.getElementById('host-status')?.textContent??'').catch(()=> '');throw new Error('数据库插件启动未完成：'+message);}return this.page;}
 async before(userText:string,signal?:AbortSignal){const job=this.busy.then(async()=>{if(signal?.aborted)throw new Error('数据库准备已取消');const abort=()=>{void this.close()};signal?.addEventListener('abort',abort,{once:true});try{const page=await this.ensure();return await page.evaluate(text=>(window as any).LiyuanDatabasePluginHost.before(text),userText);}finally{signal?.removeEventListener('abort',abort)}});this.busy=job.catch(()=>{});return job;}
 async after(sourceEntryId?:string,signal?:AbortSignal){const job=this.busy.then(async()=>{if(signal?.aborted)throw new Error('数据库整理已取消');const abort=()=>{void this.close()};signal?.addEventListener('abort',abort,{once:true});this.http.boundSourceEntryId=sourceEntryId;try{const page=await this.ensure();return await page.evaluate(()=>(window as any).LiyuanDatabasePluginHost.after());}finally{this.http.boundSourceEntryId=undefined;signal?.removeEventListener('abort',abort);}});this.busy=job.catch(()=>{});return job;}
 async rpc(method:string,args:unknown[]=[]){const page=await this.ensure();return page.evaluate(({method,args})=>(window as any).LiyuanDatabasePluginHost.rpc(method,args),{method,args});}
 status(){return {connected:!!this.page,scope:this.scope};}
}
